#!/bin/zsh

# ImageMagick (magick)
# collection of tools to modify and manipulate images
# https://imagemagick.org

appname=ImageMagick
cliname=magick
dirname=$appname
pkgname=imagemagick

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    brew install -q $pkgname
else
    verinfo $cliname "$appname"
fi
