#!/bin/zsh

# read su password
sudo printf ''

# ffmpeg
# Play, record, convert, and stream audio and video
# https://ffmpeg.org/
printhead 'Installing ffmpeg...'
install-ffmpeg

# ImageMagick (magick)
# collection of tools to modify and manipulate images
# https://imagemagick.org
printhead 'Installing imagemagick...'
install-imagemagick

# Exiftool
# Perl lib for reading and writing EXIF metadata
# https://exiftool.org
printhead 'Installing exiftool...'
install-exiftool

# yt-dlp
# YouTube video downloader
# https://github.com/yt-dlp/yt-dlp
printhead 'Installing yt-dlp...'
install-ytdlp

printhead 'Multimedia shell tools installation completed.'
