#!/bin/zsh

# nnn
# Tiny, lightning fast, feature-packed file manager
# https://github.com/jarun/nnn

appname=nnn
cliname=$appname
dirname=$appname
pkgname=$appname
vercmmd="-V"

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q $pkgname
    else
        aptinstall $cliname
    fi
    echo "==> Installing nnn plugins..."
    sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)" &>/dev/null
else
    verinfo $cliname "$appname" $vercmmd
fi

# Symlink bookmarks
mkdir -p $CONFDIR/nnn
if [[ -f $CONFDIR/nnn/bookmarks ]]; then
    rm -f $CONFDIR/nnn/bookmarks
fi
ln -sfF $GHCONFDIR/nnn/bookmarks $CONFDIR/nnn/bookmarks
