#!/bin/zsh

# nvim (neovim)
# hyperextensible Vim-based text editor
# https://neovim.io/

appname="Neovim"
cliname=nvim
brewname=nvim
aptname=null
verswitch="--version"

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
verinfo $cliname "$appname" "$verswitch"

# Default editor in Debian-based systems
if [[ ! "$(osname)" == "macos" ]]; then
    sudo update-alternatives --install /usr/bin/editor editor /usr/local/bin/nvim 1000
fi

# Configuration files
mkdir -p ~/.config/nvim
lns "$GHCONFDIR/nvim" "$CONFDIR/nvim"

# NeoVim Python
npm install -g neovim

# LSP
appname="Lua Language Server"
cliname=lua-language-server
brewname=lua-language-server
aptname=null

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
