#!/bin/zsh

# oh-my-zsh (omz)
# an open source framework for managing zsh configuration
# https://ohmyz.sh
# https://github.com/ohmyzsh/ohmyzsh

printhead 'Installing oh-my-zsh...'

[[ ! -n $ZSH ]] && ZSH=$HOME/.config/omz
[[ ! -n $ZSH_CUSTOM ]] && ZSH_CUSTOM=$ZSH/custom

if [[ $(isomzinstalled) == 0 ]]; then
    [[ -f $TMPDIR/.zshrc ]] && rm -f $TMPDIR/.zshrc
    cp $ZDOTDIR/.zshrc $TMPDIR/.zshrc
    printinfo ".zshrc backed up to $TMPDIR/.zshrc"
    omzinstall=https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    export ZSH="$CONFDIR/omz"
    sh -c "$(curl -fsSL $omzinstall)" "" --unattended --keep-zshrc
    rm -rf "$CONFDIR/zsh"
    lns "$GHCONFDIR/zsh" "$ZDOTDIR"
    lns "$GHCONFDIR/zsh/.zshenv" "$HOME/.zshenv"
    omzversion
else
    [[ -f $ZSH/oh-my-zsh.sh ]] && source $ZSH/oh-my-zsh.sh
    omz update
    omzversion
fi

# Fish-like fast/unobtrusive autosuggestions
installomzplugin zsh-autosuggestions

# Fish shell-like syntax highlighting
installomzplugin zsh-syntax-highlighting
