#!/bin/zsh

# ca-certificates
# Mozilla CA certificate store
# https://curl.se/docs/caextract.html

printhead 'Installing certificates...'

if [[ $(isinstalledbybrew ca-certificates) -eq 0 ]]; then
    brew install -q ca-certificates
else
    ver=$(brew list ca-certificates | grep -oE '\b[0-9]{4}-[0-9]{2}-[0-9]{2}\b' | head -1)
    echo "ca-certificates from $ver is installed."
fi
