#!/bin/zsh

# git
# distributed version control system
# https://git-scm.com

appname='git'
cliname='git'
brewname=null
aptname='git'

printhead "Installing git..."
if [[ "$(osname)" == "macos" ]]; then
    if [[ $(isinstalled $cliname) -eq 0 ]]; then
        xcode-select --install
    fi
else
    export LC_ALL="en_US.UTF-8"
    export LC_CTYPE="en_US.UTF-8"
    installapp $cliname $brewname $aptname "$appname"
fi
verinfo $cliname "$appname" "$verswitch"

if [[ -z "$(git config --global user.email)" ]]; then
    git config --global user.email "abarabasz@gmail.com"
    git config --global user.name "Andrzej Barabasz"
    git config --global core.pager bat
    git config --global core.editor code
fi
