#!/bin/zsh

# Brew core packages

printhead "Installing brew core packages..."

if isinstalled brew; then
    brew install -q gmp isl mpfr libmpc lz4 xz bzip2 zlib zstd binutils m4 pkgconf openssl@3 readline libxcrypt sqlite
else
    echo "Brew is not installed"
fi
