#!/bin/zsh

# gh - GitHub CLI
# GitHub CLI brings GitHub to your terminal
# https://cli.github.com

appname='GitHub CLI'
cliname='gh'
brewname='gh'
aptname=null

installapp $cliname $brewname $aptname "$appname"
lnsconfdir $cliname
verinfo $cliname "$appname" "$verswitch"

if [[ "$(gh auth status | grep -o 'Logged')" == "Logged" ]]; then
    gh auth status | grep 'Logged'
else
    gh auth login
fi
