#!/bin/zsh

# zzz
# put mac to sleep
# https://github.com/Orc/Zzz

appname=Zzz
cliname=zzz
brewname=zzz
aptname=null

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
# verinfo $cliname "$appname" "$verswitch" # zzz does not have a version option
