#!/bin/zsh

if [[ $(isinstalled python3) -eq 0 ]]; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q python3
    else
        aptinstall python3
        aptinstall python3-pip
    fi
else
    python3 --version
fi

if [[ $(isinstalled pip) -eq 0 ]]; then
    if [[ "$(osname)" != "macos" ]]; then
        aptinstall python3-pip
    fi
else
    pip --version    
fi