#!/bin/zsh

# coreutils
# GNU core utilities
# https://www.gnu.org/software/coreutils/

loginfiles

appname='GNU core utilities'
cliname='gdate'
brewname='coreutils'
aptname=''

installapp $cliname $brewname $aptname $appname


