#!/bin/zsh

# Lynx
# console web browser
# https://www.lynxcloud.app/

appname='Lynx Web Browser'
cliname=lynx
dirname=$cliname
pkgname=$cliname

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    brew install -q $pkgname
else
    verinfo $cliname "$appname"
fi