#!/bin/zsh

# Node.js
# JavaScript runtime environment
# https://github.com/jarun/nnn

if [[ $(isinstalled node) -eq 0 ]]; then
    brew install -q node
else
    echo "Node.js version $(node --version)"
fi

# Node basic config
npm config set fund false --location=global

# typescript
# https://github.com/microsoft/TypeScript

npm install -gD typescript

# tsx - TypeScript Execute
# https://github.com/privatenumber/tsx

npm install -g tsx