#!/bin/zsh

# fzf
# Command-line fuzzy finder written in Go
# https://github.com/junegunn/fzf

appname=fzf
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    brew install -q $pkgname
else
    verinfo $cliname "$appname"
fi
