#!/bin/zsh

# cmake
# Cross-platform make
# https://cmake.org/

appname="cmake"
cliname="cmake"
brewname="cmake"
aptname="cmake"

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
[[ $(isinstalled brew) -eq 0 ]] && brew install -q $brewname
verinfo $cliname "$appname" "$verswitch"
