#!/bin/zsh

# read su password
sudo printf ''

# Pyhon & pip
printhead 'Installing Python...'
install-python
printinfo 'Install oficiall Python as well (python.org/downloads)'

# Node
printhead 'Installing Node...'
install-node

# PHP
printhead 'Installing PHP...'
install-php
printhead 'Installing PHP Composer...'
install-composer

# Lua
printhead 'Installing Lua...'
install-lua

printinfo 'Installation completed.'