#!/bin/zsh

# kitty
# The fast, feature-rich, GPU based terminal emulator
# https://sw.kovidgoyal.net/kitty/

appname=kitty
cliname=$appname
brewname=$appname
aptname=$appname

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
verinfo $cliname "$appname" "$verswitch"

lnsconfdir $appname
