#!/bin/zsh

# yt-dlp
# YouTube video downloader
# https://github.com/yt-dlp/yt-dlp

appname=yt-dlp
cliname=$appname
dirname=$appname
pkgname=$appname

if isinstalled $cliname; then
    brew install -q $pkgname
else
    verinfo $cliname "$appname"
fi
