#!/bin/zsh

# eza
# modern alternative for the ls
# https://github.com/eza-community/eza

appname=eza
cliname=$appname
dirname=$appname
pkgname=$appname

if [[ $(isinstalled $cliname) -eq 0 ]]; then
    brew install -q $pkgname
else
    verinfo $cliname "$appname"
fi