#!/bin/zsh

# remote files
enm="Environment variables"
enf="https://raw.githubusercontent.com/barabasz/config/main/zsh/.zvars"
lbm="Functions library"
lbf="https://raw.githubusercontent.com/barabasz/lib/main/_all.sh"
ghd="https://raw.githubusercontent.com/barabasz/bin/main/install"

# messages
msg_title="Base system components installation"
msg_warn="This script will install base system components."
msg_ok="Core installation completed."
msg_reload="Reload terminal to apply changes."

# initial main loading function
function source_remote_lib() {
    local url=$1 name=$2 file_content=""
    file_content=$(wget -q -O - $url)
    [[ $? -ne 0 ]] && { echo "Error getting $name ($url)."; return 1; }
    source /dev/stdin <<< "$file_content"
    [[ $? -ne 0 ]] && { echo "Error sourcing $name."; return 1; }
    echo "$name successfully loaded."
}
alias srl="source_remote_lib"
alias sr="source_remote"

srl $enf "$enm" || exit 1    # loading environment variables
srl $lbf "$lbm" || exit 1    # loading functions library

printtitle "$msg_title"      # script title
log::warn "$msg_warn"        # warning message
prompt_continue || exit 0    # prompt to continue

sr $ghd/install-sudo         # sudo if not installed (Debian)
sudo echo > /dev/null        # force sudo password prompt
needrestart-quiet            # disable NEEDRESTART prompt (Ubuntu)
sr $ghd/install-dirs         # creating base directories
sr $ghd/install-locales      # generate locale (Ubuntu/Debian)

sysupdate                    # update and upgrade

sr $ghd/install-git          # Git
sr $ghd/install-repos        # main public repositories
sr $ghd/install-symlinks     # symlinks
sr $ghd/install-zsh          # zsh  

# from here on, scripts are available in the PATH

# Brew and basic libraries

install-brew                 # Homebrew
install-certs                # Certificates
install-brew-core            # Basic brew libraries
install-ncurses              # Text-based UI library
install-gcc                  # GNU compiler collection
install-cmake                # Cross-platform make

# Shell enhancements

install-omz                  # oh-my-zsh
install-omp                  # oh-my-posh

# System utilities

install-7zip                 # 7zip
install-acl                  # POSIX access control lists (Linux only)
install-bat                  # cat with syntax highlighting
install-bc                   # bc
install-calc                 # arbitrary precision calculator
install-curl                 # curl
install-exiftool             # read and write EXIF metadata
install-eza                  # modern alternative for the ls
install-fd                   # find entries in your filesystem
install-fzf                  # fzf fuzzy finder
install-ffmpeg               # ffmpeg
# install-fonts              # fonts 
install-gh                   # GitHub CLI
install-glow                 # markdown reader
install-gzip                 # gzip
install-htop                 # improved top
install-httpserver           # command-line http server
install-imagemagick          # ImageMagick
install-lsd                  # better GNU ls
install-lynx                 # console web browser
install-mc                   # Midnight Commandern
install-navi                 # cheatsheet tool
install-nnn                  # nnn file manager
install-nvim                 # hyperextensible Vim-based text editor
install-repos-priv           # private repositories
install-ripgrep              # line-oriented search tool for files
install-rmlint               # extremely fast tool to remove dupes
install-thefuck              # The Fuck
install-tldr                 # tldr
install-tmux                 # tmux
install-util-linux           # Brew linux utilities (Mac only)
install-wget                 # wget
install-ytdlp                # YouTube downloader
install-zoxide               # smarter cd command, inspired by z
install-zzz                  # put mac to sleep

# post-installation tasks

minimize-login-info          # disable login info
set-warsaw-timezone          # setting timezone (Linux)
remove-snap                  # remove snap (Ubuntu)

log::ok $msg_ok              # success message
log::info $msg_reload        # reload message

exec zsh                     # attempt to auto-reload shell
