#!/bin/zsh

if ! isinstalled php; then
    if [[ "$(osname)" == "macos" ]]; then
        brew install -q php
    else
        sudo add-apt-repository -y ppa:ondrej/php
        sudo apt-get update > /dev/null
        aptinstall php8.2
        aptinstall php8.2-{bcmath,fpm,xml,mysql,zip,intl,ldap,gd,cli,bz2,curl,mbstring,opcache,soap,cgi}
    fi
else
    php --version | grep 'built'
fi

