#!/bin/zsh

printhead 'Cloning setup repositories...'

mkdir -p ~/GitHub && cd $_

repos=("bin" "config" "lib")
for repo in "${repos[@]}"; do
    # rm -rf $repo # to reinstall use reinstall-repos
    echo "Cloning $repo..."
    git clone "https://github.com/barabasz/${repo}.git"
    log::info "$repo successfully cloned."
done

