#!/bin/zsh

# 7zip
# file archiver with a high compression ratio
# https://7-zip.org

appname="7-zip"
cliname=7zz
brewname=sevenzip
aptname=sevenzip
verswitch=help

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
verinfo $cliname "$appname" "$verswitch"
