#!/bin/zsh

# yazi
# terminal file manager written in Rust
# https://github.com/sxyazi/yazi

appname="Yazi"
cliname=yazi
dirname=yazi
brewname=yazi
aptname=yazi
verswitch="--version"

installapp $cliname $brewname $aptname "$appname"
verinfo $cliname "$appname" "$verswitch"
lnsconfdir $dirname

# Plugins

# https://github.com/yazi-rs/plugins/tree/main/mount.yazi
ya pack -a yazi-rs/plugins:mount

# https://github.com/yazi-rs/plugins/tree/main/full-border.yazi
ya pack -a yazi-rs/plugins:full-border

# https://github.com/yazi-rs/plugins/tree/main/git.yazi
ya pack -a yazi-rs/plugins:git

# https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi
ya pack -a yazi-rs/plugins:smart-enter

# https://github.com/yazi-rs/plugins/tree/main/smart-filter.yazi
ya pack -a yazi-rs/plugins:smart-filter

# https://github.com/yazi-rs/plugins/tree/main/mime-ext.yazi
ya pack -a yazi-rs/plugins:mime-ext

# https://github.com/boydaihungst/mediainfo.yazi
ya pack -a boydaihungst/mediainfo

# https://github.com/Reledia/glow.yazi
ya pack -a Reledia/glow.yazi

# Theme

# Dracula: https://draculatheme.com/yazi
[[ ! -d ~/.config/yazi/flavors ]] && mkdir -p ~/.config/yazi/flavors
[[ -d ~/.config/yazi/flavors/dracula.yazi ]] && rm -rf ~/.config/yazi/flavors/dracula.yazi
git clone https://github.com/dracula/yazi.git ~/.config/yazi/flavors/dracula.yazi