#!/bin/zsh

# espanso
# A Privacy-first, Cross-platform Text Expander
# https://espanso.org

appname=espanso
cliname=$appname
brewname=$appname
aptname=$appname

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
verinfo $cliname "$appname" "$verswitch"

lnsconfdir -p $appname