#!/bin/zsh

# mc (Midnight Commander)
# feature rich full-screen text mode visual file manager
# https://midnight-commander.org/

cliname='mc'
brewname='midnight-commander'
aptname='mc'
appname='Midnight Commander'
dirname='mc'

installapp $cliname $brewname $aptname "$appname"
verinfo $cliname "$appname" "$verswitch"
lnsconfdir $dirname

mkdir -p ~/.local/share/mc
lns $HOME/GitHub/config/mc/skins $HOME/.local/share/mc/skins