#!/bin/zsh

# zoxide (z)
# smarter cd command, inspired by z and autojump
# https://github.com/ajeetdsouza/zoxide

appname=zoxide
cliname=$appname
dirname=$appname
pkgname=$appname

if isinstalled $cliname; then
    brew install -q $pkgname
else
    verinfo $cliname "$appname"
fi

lnsconfdir $dirname