#!/bin/zsh

# bat
# A cat clone with syntax highlighting
# https://github.com/sharkdp/bat

appname="bat"
cliname=bat
brewname=bat
aptname=bat

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
lnsconfdir $cliname
verinfo $cliname "$appname" "$verswitch"
