#!/bin/zsh

# Exiftool
# Perl lib for reading and writing EXIF metadata
# https://exiftool.org

if [[ $(isinstalled exiftool) -eq 0 ]]; then
    brew install -q exiftool
else
    echo exiftool $(exiftool -ver)
fi