#!/bin/zsh

# gcc
# GNU compiler collection
# https://gcc.gnu.org/

appname="GNU Compiler Collection"
cliname="gcc"
brewname="gcc"
aptname="gcc"

printhead "Installing $appname..."
installapp $cliname $brewname $aptname "$appname"
[[ $(isinstalled brew) -eq 0 ]] && brew install -q $brewname
verinfo $cliname "$appname" "$verswitch"

