#!/bin/zsh

# ncurses
# Text-based UI library
# https://invisible-island.net/ncurses/

printhead "Installing ncurses..."

if [[ $(isinstalledbybrew ncurses) -eq 0 ]]; then
    brew install -q ncurses
else
    brew list ncurses | grep "bin/ncurses"
fi
