#!/bin/zsh

printhead "Creating symlinks..."

# Common scripts
[[ ! -d $BINDIR ]] && mkdir -p $BINDIR
lns "$GHBINDIR/common" "$BINDIR/common"
lns "$GHBINDIR/install" "$BINDIR/install"
lns "$GHBINDIR/test" "$BINDIR/test"

# OS-specific scripts
if [[ "$(osname)" == "macos" ]]; then
    lns "$GHBINDIR/macos" "$BINDIR/thisos"
else
    lns "$GHBINDIR/linux" "$HOME/thisos"
fi

# Library
lns "$GHLIBDIR" "$LIBDIR"

# zsh
rm -f $HOME/.zshrc
rm -f $HOME/.zprofile
rm -f $HOME/.zlogin
rm -f $HOME/.zlogout
lns "$GHCONFDIR/zsh" "$ZDOTDIR"
lns "$GHCONFDIR/zsh/.zshenv" "$HOME/.zshenv"

# bash fallback
lns "$GHCONFDIR/bash/.bashrc" "$HOME/.bashrc"
lns "$GHCONFDIR/bash/.bash_profile" "$HOME/.bash_profile"

